//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CreateTime { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string QQNum { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public string Hobby { get; set; }
        public string Motto { get; set; }
        public Nullable<int> SupportTimes { get; set; }
        public string Remarks { get; set; }
    }
}
